# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fabworkcenters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FabWorkcenters',
        ),
    ]
