# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.CharField(max_length=4)),
                ('primary_material', models.CharField(max_length=16)),
                ('primary_stabilizer', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Fab Composition',
                'verbose_name_plural': 'Fab Compositions',
            },
        ),
        migrations.CreateModel(
            name='FabProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fabworkcenters',
            options={'verbose_name': 'Fab Workcenter', 'verbose_name_plural': 'Fab Workcenters'},
        ),
    ]
